include:
  - ".well-known"
  - ".htaccess"

# Exclude these files from production site
exclude:
  - package.json
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-sitemap

# Output options
timezone: America/Sao_Paulo
encoding: utf-8
layout: default

# Name of website
title: Developers - R4 Digital
noindex: true

# Facebook App ID
#fb_app_id: ""


